### ISSUE TITLE
Todo v1

### ISSUE THREAD

**Issue by chk1** [chk1/geohash#1]
- [x] converts lon/lat to and from geohash data
- [ ] create classes and methods for (point and line) data that are encoded using geohash (conversion, plot, summary)
- [ ] take care of the error in the conversion, and plot symbol size / line width / bounding box according to this error / approximation
